project_meta:
  _target_: DeSpAn.config._ProjectMeta
  name: Project
  epoch1_name: Epoch1
  epoch2_name: Epoch2

app_settings:
  _target_: DeSpAn.config._AppSettings
  retain_intensities: True
  filter_ground_points: True
  greedy_directory_search: True
  greedy_file_types:
    - laz
    - las

paths:
  _target_: DeSpAn.config._Paths
  pcd_e1:
  pcd_e2:
  intermediate_results:
  CC_exe: C:\Program Files\CloudCompare\CloudCompare.exe
  m3c2_settings: E:\13_REASSESS\99_code\src\DeSpAn\conf\m3c2\m3c2_params_0.2_0.2_2_proj_0.3.txt
  hsv_settings:  E:\13_REASSESS\99_code\src\DeSpAn\conf\m3c2\HSV_5mm.xml