project_meta:
  name: Flamatt
  epoch1_name: 2018-03-22
  epoch2_name: 2020-03-04

app_settings:
  retain_intensities: True
  filter_ground_points: True
  greedy_directory_search: True
  greedy_file_types:
    - laz
    - las

paths:
  pcd_e1: E:\13_REASSESS\00_test_data\Flamatt\01_Input\20180322_Lausanne_Bern_U204134_Fabing_Helimap\Raw\LiDAR
  pcd_e2: E:\13_REASSESS\00_test_data\Flamatt\01_Input\20200304_Flamatt_U225557_Ackermann_Helimap\Raw\LiDAR
  intermediate_results: E:\13_REASSESS\00_test_data\Flamatt\02_intermediate