project_meta:
  name: ROSS
  epoch1_name: 2020
  epoch2_name: 2022

app_settings:
  retain_intensities: True
  filter_ground_points: True
  greedy_directory_search: True
  greedy_file_types:
    - laz
    - las
    - ply

paths: # Paths can either be defined absolute or with respect to base DeSpAn module folder
  pcd_e1: C:\scratch\16_SBB_F2S3\01_data\00_ingest\2020_ROSS\01_LAZ
  pcd_e2: C:\scratch\16_SBB_F2S3\01_data\00_ingest\2022_ROS2\01_LAZ
  intermediate_results: C:\scratch\16_SBB_F2S3\01_data\01_processing\01_filtered_ground_points